---
title: "census data pull"
author: "Annabel Tan"
date: "2023-12-03"
output: html_document
---
```{r, message=FALSE}
#install.packages("censusapi")
library(censusapi)
library(tidycensus)


# Add key to .Renviron
Sys.setenv(CENSUS_KEY="5abd069283f37d9dfd150854b41837507e2ce9ca")
# Reload .Renviron
#readRenviron("~/.Renviron")
# Check to see that the expected key is output in your R console
Sys.getenv("CENSUS_KEY")

CENSUS_KEY = "5abd069283f37d9dfd150854b41837507e2ce9ca"

#Get Available APIs

apis <- listCensusApis()

```


Pull population by ZCTA for years 2013:2020
```{r}
#2020 didnt have adequate census reporting so i will assume 2019 = 2020 data

years = 2013:2019
population_data_list <- list()
for (year in years){
  population_data <- get_acs(
    geography = "zip code tabulation area",
    variables = "B01003_001",
    state = "06", # Specify California
    survey = "acs5", # Use the 5-year ACS data
    year = year # Specify one year within the 5-year range
  )

  population_data_list[[as.character(year)]] <- population_data
  
  # Pause for a few seconds to avoid overwhelming the API (optional)
  Sys.sleep(1)
}

population_data_2013 <- population_data_list[["2013"]]
population_data_2014 <- population_data_list[["2014"]]
population_data_2015 <- population_data_list[["2015"]]
population_data_2016 <- population_data_list[["2016"]]
population_data_2017 <- population_data_list[["2017"]]
population_data_2018 <- population_data_list[["2018"]]
population_data_2019 <- population_data_list[["2019"]]
population_data_2020 <- population_data_list[["2019"]]



write.csv(population_data_2013,"population_data_2013.csv")
write.csv(population_data_2014,"population_data_2014.csv")
write.csv(population_data_2015,"population_data_2015.csv")
write.csv(population_data_2016,"population_data_2016.csv")
write.csv(population_data_2017,"population_data_2017.csv")
write.csv(population_data_2018,"population_data_2018.csv")
write.csv(population_data_2019,"population_data_2019.csv")
write.csv(population_data_2020,"population_data_2020.csv")

#MERGE ALL POP FILES TOGETHER
# Set the path to your folder
folder_path <- "data_population"

# Get a list of all files in the folder
file_list <- list.files(path = folder_path, full.names = TRUE)

# Define a function to read and load a file
load_file <- function(file_path) {
  # Modify the following line based on the file format and loading method
  # For example, if you're working with CSV files, you can use read.csv
  data <- read.csv(file_path, header = TRUE, sep = ",")
  return(data)
}

# Use lapply to apply the load_file function to each file in the list
loaded_data <- lapply(file_list, load_file)

# Alternatively, if you want to combine all loaded data into a single data structure
combined_data <- do.call(rbind, loaded_data)  

combined_data = combined_data %>%
  select(-X, -NAME, -variable) %>%
  rename(zip = GEOID)

write.csv(combined_data,"population_COMPLETE.csv")

```

urban/rural by zipcode
P002001 -	 Total pop
P002002 - Urban pop
```{r}
urban_rural_population <- get_decennial(
  geography = "zcta",
  variables = c("P002001", "P002002", "P002005"), # Example variables for total population and urban population
  state = "06", # California state code
  year = 2010,
  survey = "sf1"
)

urb_rural_wide = urban_rural_population %>%
    pivot_wider(
    names_from = variable,
    values_from = c(value)
  )

urb_rural_wide = urb_rural_wide %>%
  mutate(urbanpercentage = (P002002/P002001)) %>%
  mutate(ruralpercentage = (P002005/P002001))  %>%
  mutate(rural = ifelse(ruralpercentage > urbanpercentage, 1, 0))%>%
  mutate(zip= substr(GEOID, nchar(GEOID) - 4, nchar(GEOID)))


urb_rural_wide1 = urb_rural_wide %>%
  select(zip, rural)


write.csv(urban_rural_population, "urban_rural.csv")
write.csv(urb_rural_wide1, "urb_rural_binary.csv")


```
Gini coefficient by zipcode
```{r}

#2020 didnt have adequate census reporting so i will assume 2019 = 2020 data
years = 2013:2019
gini_data_list <- list()
for (year in years){
  gini_data <- get_acs(
    geography = "zip code tabulation area",
    variables = "B19083_001E",
    state = "06", # Specify California
    survey = "acs5", # Use the 5-year ACS data
    year = year # Specify one year within the 5-year range
  )

  gini_data_list[[as.character(year)]] <- gini_data
  
  # Pause for a few seconds to avoid overwhelming the API (optional)
  Sys.sleep(1)
}

gini_data_2013 <- gini_data_list[["2013"]]
gini_data_2014 <- gini_data_list[["2014"]]
gini_data_2015 <- gini_data_list[["2015"]]
gini_data_2016 <- gini_data_list[["2016"]]
gini_data_2017 <- gini_data_list[["2017"]]
gini_data_2018 <- gini_data_list[["2018"]]
gini_data_2019 <- gini_data_list[["2019"]]
gini_data_2020 <- gini_data_list[["2019"]]

write.csv(gini_data_2013, "gini_data_2013.csv")
write.csv(gini_data_2014, "gini_data_2014.csv")
write.csv(gini_data_2015, "gini_data_2015.csv")
write.csv(gini_data_2016, "gini_data_2016.csv")
write.csv(gini_data_2017, "gini_data_2017.csv")
write.csv(gini_data_2018, "gini_data_2018.csv")
write.csv(gini_data_2019, "gini_data_2019.csv")
write.csv(gini_data_2020, "gini_data_2020.csv")

```

median housing structure built
```{r}

years = 2013:2019
housing_data_list <- list()
for (year in years){
  housing_data <- get_acs(
    geography = "zip code tabulation area",
    variables =  c("B25034_001E", "B25034_005E", "B25034_006E"),
    state = "06", # Specify California
    survey = "acs5", # Use the 5-year ACS data
    year = year # Specify one year within the 5-year range
  )

 housing_data_list[[as.character(year)]] <- housing_data
  
  # Pause for a few seconds to avoid overwhelming the API (optional)
  Sys.sleep(1)
}

housing_data_2013 <- housing_data_list[["2013"]]
housing_data_2014 <- housing_data_list[["2014"]]
housing_data_2015 <- housing_data_list[["2015"]]
housing_data_2016 <- housing_data_list[["2016"]]
housing_data_2017 <- housing_data_list[["2017"]]
housing_data_2018 <- housing_data_list[["2018"]]
housing_data_2019 <- housing_data_list[["2019"]]
housing_data_2020 <- housing_data_list[["2019"]]

write.csv(housing_data_2013, "housing_data_2013.csv")
write.csv(housing_data_2014, "housing_data_2014.csv")
write.csv(housing_data_2015, "housing_data_2015.csv")
write.csv(housing_data_2016, "housing_data_2016.csv")
write.csv(housing_data_2017, "housing_data_2017.csv")
write.csv(housing_data_2018, "housing_data_2018.csv")
write.csv(housing_data_2019, "housing_data_2019.csv")
write.csv(housing_data_2020, "housing_data_2020.csv")


```

